//Goods Sold
export const naceDict = {
  closed: "0.0",
  groceryStore: "52.1.1",
  generalStore: "52.2.2",
  produce: "52.2.1",
  butcher: "52.2.2",
  seafood: "52.2.3",
  bakery: "52.2.4.1",
  candy: "52.2.4.2",
  liquor: "52.2.5.1",
  wine: "52.2.5.2",
  tobacco: "52.2.6",
  pharmacy: "52.3.1",
  medicalGoods: "52.3.2",
  cosmetics: "52.3.3",
  perfume: "52.3.3.1",
  textile: "52.4.1",
  clothing: "52.4.2",
  luxury: "52.4.2.1",
  undergarments: "52.4.2.2",
  accessories: "52.4.2.3",
  shoes: "52.4.3.1",
  leatherGoods: "52.4.3.2",
  gloves: "52.4.3.3",
  furniture: "52.4.4.1",
  householdGoods: "52.4.4.2",
  radioTelevision: "52.4.5.1",
  computers: "52.4.5.2",
  electronics: "52.4.5.3",
  hardwareStore: "52.4.6",
  books: "52.4.7.1",
  newspapers: "52.4.7.2",
  stationary: "52.4.7.3",
  otherRetail: "52.4.8",
  petStore: "52.4.8.1",
  art: "52.4.8.2",
  boatSupplies: "52.4.8.3",
  coinsStamps: "52.4.8.4",
  costumes: "52.4.8.5",
  opticalStore: "52.4.8.6",
  fishing: "52.4.8.7",
  frames: "52.4.8.8",
  florist: "52.4.8.9",
  funeralGoods: "52.4.8.10",
  jewelry: "52.4.8.11",
  knives: "52.4.8.12",
  entertainment: "52.4.8.13",
  metalWork: "52.4.8.14",
  musicalInstruments: "52.4.8.15",
  officeSupplies: "52.4.8.16",
  photoStore: "52.4.8.17",
  sportingGoods: "52.4.8.18",
  souvenirs: "52.4.8.19",
  toys: "52.4.8.20",
  wedding: "52.4.8.21",
  woodWork: "52.4.8.22",
  pawnShop: "52.5.0",
  antiques: "52.5.1",
  repair: "52.7",
  hotel: "55.1",
  hotelWithRestaurant: "55.1.1",
  hotelWithoutRestaurant: "55.1.2",
  hostel: "55.2.1",
  bedBreakfast: "55.2.3.1",
  affitacamere: "55.2.3.2",
  apartmentRental: "55.2.3.3",
  restaurant: "55.3.0",
  gelateria: "55.3.0.1",
  pizzeria: "55.3.0.2",
  bar: "55.4.0",
  travelAgency: "63.3.0",
  transportation: "63.4.0",
  delivery: "63.4.0.1",
  bank: "65.1.1",
  exchange: "65.1.2.1",
  moneyTransfer: "65.1.2.2",
  realEstate: "70.3.1",
  carRental: "71.1.0",
  computerServices: "72.5.0",
  photographer: "74.8.1",
  photocopy: "74.8.5",
  graphicDesign: "74.8.6",
  recreationalActivities: "92.7.2",
  dryCleaner: "93.0.1.1",
  laundromat: "93.0.1.1",
  hairSalon: "93.0.2.1",
  nailSalon: "93.0.2.2",
  spa: "93.0.2.3",
  masseuse: "93.0.2.4",
  tattoPiercing: "93.0.2.5",
  funeralServices: "93.0.3",
  fitness: "93.0.5",
  tailor: "93.0.5.1"
};

export const allTags = [
  { value: "accessories", label: "Acessories" },
  { value: "affitacamere", label: "Affitacamere" },
  { value: "antiques", label: "Antiques" },
  { value: "apartment rental", label: "Apartment Rental" },
  { value: "art", label: "Art" },
  { value: "bakery", label: "Bakery" },
  { value: "bank", label: "Bank" },
  { value: "bar", label: "Bar" },
  { value: "b&b", label: "Bed & Breakfast" },
  { value: "boat supplies", label: "Boat Supplies" },
  { value: "books", label: "Books" },
  { value: "butcher", label: "Butcher" },
  { value: "candy", label: "Candy" },
  { value: "car rental", label: "Car Rental" },
  { value: "clothing", label: "Clothing" },
  { value: "coffee", label: "Coffee" },
  { value: "coins & stamps", label: "Coins & Stamps" },
  { value: "computers", label: "Computers" },
  { value: "computer services", label: "Computer Services" },
  { value: "cosmetics", label: "Cosmetics" },
  { value: "costumes", label: "Costumes" },
  { value: "dairy", label: "Dairy" },
  { value: "delivery", label: "Delivery" },
  { value: "dry cleaner", label: "Dry Cleaner" },
  { value: "electronics", label: "Electronics" },
  { value: "entertainment", label: "Entertainment" },
  { value: "exchange", label: "Exchange" },
  { value: "florist", label: "Florist" },
  { value: "fish", label: "Fish" },
  { value: "fitness", label: "Fitness" },
  { value: "funeral", label: "Funeral Goods" },
  { value: "furniture", label: "Furniture" },
  { value: "gelateria", label: "Gelateria" },
  { value: "general store", label: "General Store" },
  { value: "gloves", label: "Gloves" },
  { value: "graphic design", label: "Graphic Design" },
  { value: "grocery store", label: "Grocery Store" },
  { value: "hardware store", label: "Hardware Store" },
  { value: "hair salon", label: "Hair Salon" },
  { value: "household goods", label: "Household Goods" },
  { value: "hostel", label: "Hostel" },
  { value: "hotel", label: "Hotel" },
  { value: "hotel with restaurant", label: "Hotel with Restaurant" },
  { value: "hotel without restaurant", label: "Hotel without Restaurant" },
  { value: "jewelry", label: "Jewelry" },
  { value: "knives", label: "Knives" },
  { value: "laundromat", label: "Laundromat" },
  { value: "leather goods", label: "Leather Goods" },
  { value: "liquor", label: "Liquor" },
  { value: "luxury", label: "Luxury" },
  { value: "masseuse", label: "Masseuse" },
  { value: "medical goods", label: "Medical Goods" },
  { value: "metal works", label: "Metal Works" },
  { value: "money transfer", label: "Money Transfer" },
  { value: "musical instuments", label: "Musical Instruments" },
  { value: "nail salon", label: "Nail Salon" },
  { value: "office supplies", label: "Office Supplies" },
  { value: "optical stores", label: "Optical Stores" },
  {
    value: "other recreational activities",
    label: "Other Recreational Activities"
  },
  { value: "pet store", label: "Pet Store" },
  { value: "perfumes", label: "Perfumes" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "photocopy", label: "Photocopy" },
  { value: "photographer", label: "Photographer" },
  { value: "photo store", label: "Photo Store" },
  { value: "pizzeria", label: "Pizzeria" },
  { value: "produce", label: "Produce" },
  { value: "real estate", label: "Real Estate" },
  { value: "repair services", label: "Repair Services" },
  { value: "restaurant", label: "Restaurant" },
  { value: "shoes", label: "Shoes" },
  { value: "souvenirs", label: "Souvenirs" },
  { value: "spa", label: "Spa" },
  { value: "sporting goods", label: "Sporting Goods" },
  { value: "stationary", label: "Stationary" },
  { value: "tailor", label: "Tailor" },
  { value: "tattoo & piercing", label: "Tatto & Piercing" },
  { value: "textile", label: "Textile" },
  { value: "tobacco store", label: "Tobacco Store" },
  { value: "transportation", label: "Transportation" },
  { value: "travel agency", label: "Travel Agency" },
  { value: "toys", label: "Toys" },
  { value: "undergarments", label: "Undergarments" },
  { value: "wedding", label: "Wedding" },
  { value: "wine", label: "Wine" },
  { value: "wood works", label: "Wood Works" }
];
